### ISSUE TITLE
我在tview的issues中找到了在程序中修改字符集的方法

### ISSUE THREAD

**Issue by kaze-k** [yaocccc/bilibili_live_tui#1]
https://github.com/xtaci/safebox/blob/main/charset_other.go

**Comment by yaocccc** [comment]
我尝试下把这个直接写进代码就不需要手动配置了

**Comment by yaocccc** [comment]
试了下好像不太行，mmp

**Comment by kaze-k** [comment]
我的环境是可以的
如下：
![repetition](https://user-images.githubusercontent.com/74790971/204203768-f3ab97fc-a1e8-43a6-8537-e3e4d6b9dec7.gif)
我的环境：
![neofetch](https://user-images.githubusercontent.com/74790971/204204121-f5d1c7f0-dcad-4445-9b46-e44b93b88236.png)

**Comment by yaocccc** [comment]
> 我的环境是可以的 如下： ![repetition](https://user-images.githubusercontent.com/74790971/204203768-f3ab97fc-a1e8-43a6-8537-e3e4d6b9dec7.gif) [ ![repetition](https://user-images.githubusercontent.com/74790971/204203768-f3ab97fc-a1e8-43a6-8537-e3e4d6b9dec7.gif) ](https://user-images.githubusercontent.com/74790971/204203768-f3ab97fc-a1e8-43a6-8537-e3e4d6b9dec7.gif) [ ](https://user-images.githubusercontent.com/74790971/204203768-f3ab97fc-a1e8-43a6-8537-e3e4d6b9dec7.gif) 我的环境： ![neofetch](https://user-images.githubusercontent.com/74790971/204204121-f5d1c7f0-dcad-4445-9b46-e44b93b88236.png)

奇怪哈，我又用不同的terminal实验了一下，还是不行的。你的代码是怎么写的？

我直接才main.go 里写了 os.Setenv("LANG", "en_US.utf-8")

但是不太行

**Comment by yaocccc** [comment]
先把这个关掉了

**Comment by kaze-k** [comment]
![屏幕截图 2022-12-11 205130](https://user-images.githubusercontent.com/74790971/206904639-a246f10e-793a-4550-9687-bfaf1d2c01ee.png)
这是我修改的，如果是这样的话应该是没有问题了，直接写os.Setenv()我之前试过也是不行，才在框架的issue中找到这个可行方法的

**Comment by yaocccc** [comment]
> ![屏幕截图 2022-12-11 205130](https://user-images.githubusercontent.com/74790971/206904639-a246f10e-793a-4550-9687-bfaf1d2c01ee.png) 这是我修改的，如果是这样的话应该是没有问题了，直接写os.Setenv()我之前试过也是不行，才在框架的issue中找到这个可行方法的

生效了生效了生效了，谢谢老公。
