### ISSUE TITLE
建议：对消息进行分类

### ISSUE THREAD

**Issue by soft98-top** [yaocccc/bilibili_live_tui#2]
在B站发现UP主发的视频，觉得很有意思，下载下来看了一下，提一点儿建议。
- ui层面对常见消息进行分类单独展示
  - 进入房间的消息
  - 送礼物的消息
- 如果可以的话甚至可以实现规则匹配分栏显示
  - 增加对指定字符串进行部分匹配或者正则匹配
    - 比如进入房间的消息就可以匹配字符串“进入了房间”
  - 自定义分栏名称
    - 比如主题1中的“Messages”，可以根据规则自定义对应的分栏名称
我在初次使用中发现消息堆叠导致查看不会很方便，以上是我的一点想法，UP主加油，下面附上我的截图。
<img width="588" alt="image" src="https://user-images.githubusercontent.com/68449854/211153666-67165d9f-b86f-4aec-92b1-5402bc76ab9b.png">

**Comment by yaocccc** [comment]
hhh，你刚好看了一个动态很多的房间，我一般看自己的。所以比较无感。

你这个我感觉UI不太好设计。可能单独做一个theme。把各种消息分到多个格子里

**Comment by soft98-top** [comment]
你要相信你会火的🤣，看的人多了是不是就有这个问题了，

**Comment by soft98-top** [comment]
你要相信你会火的🤣，只是建议，确实如果实现得单独搞一个主题，大哥有闲功夫的时候可以搞一下，可能后面我试着改一下代码，给你提个pr

**Comment by soft98-top** [comment]
已提pr，望采纳。

**Comment by yaocccc** [comment]
hhh，我在直播，来合并它

**Comment by yaocccc** [comment]
合并了，我更新了新东西，我感觉这个展示，像Access、Gift或者还有别的类型，其实可以共用一侧。感觉三分有点小，我试试看动态的。窗口小就把Access和Gift放到一起
